### PR TITLE
unicode_loose_md5: Fix infinite loop in Collator.

### LINKED ISSUE #1871: unicode_loose_md5 vindex type memory leak where column is binary
[pprof.zip](https://github.com/youtube/vitess/files/364447/pprof.zip)

Attached is the pprof as suggested by sougu. Also, below is the vschema:
{
  "sharded": true,
  "vindexes": {
    "hash": {
      "type": "hash"
    },
    "unicode_loose_md5": {
      "type": "unicode_loose_md5"
    }
  },
  "tables": {
    "user": {
      "column_vindexes": [
        {
          "column": "tenant_id",
          "name": "unicode_loose_md5"
        }
      ]
    }
  }
}
~

### PR DESCRIPTION
**Pull request by enisoc**
@sougou 

Fixes #1871.

I also added a sync.Pool for reusing Collators since this function is called at least once for every query that uses this vindex. If you think it's not worth it, I can remove that commit, but the microbenchmark looks good:

```
vitess/go/vt/vtgate/vindexes$ go test -bench . -benchmem
# Old thread-safe way
BenchmarkNormalizeSafe-12         200000              8331 ns/op            9784 B/op         16 allocs/op
# Fast but unsafe
BenchmarkNormalizeShared-12      3000000               455 ns/op             104 B/op          1 allocs/op
# sync.Pool
BenchmarkNormalizePooled-12      2000000               537 ns/op             134 B/op          2 allocs/op
```

---
This change is [Reviewable](https://reviewable.io/reviews/youtube/vitess/1875)

### CODE REVIEW

File: go/vt/vtgate/vindexes/unicodeloosemd5.go [hunk 1]
```diff
@@ -17,8 +19,8 @@ type UnicodeLooseMD5 struct {
 	name string
 }
 
-// MewUnicodeLooseMD5 creates a new UnicodeLooseMD5.
-func MewUnicodeLooseMD5(name string, _ map[string]string) (Vindex, error) {
+// NewUnicodeLooseMD5 creates a new UnicodeLooseMD5.
+func NewUnicodeLooseMD5(name string, _ map[string]string) (Vindex, error) {
```
Comment (sougou) [inline go/vt/vtgate/vindexes/unicodeloosemd5.go]: LOL

**Comment by sougou** [comment]
LGTM
This is awesome! I'm thinking we should file a bug against collate. No library should go OOM on invalid input.

**Comment by enisoc** [comment]
Filed https://github.com/golang/go/issues/16391
