### PR TITLE
logutil/purge: Fix timestamp parsing for -keep_logs purge feature

### LINKED ISSUE #1994: keep_logs parameter doesn;t work in VTGate/VTTablets
I tried using keep_logs parameter to purge the logs after x seconds, but it doesn;t seems to work.
While starting tablets and VTGate used keep_logs 100s as the configuration. Is there any other setting that needs to be done to make this functionality work??

### PR DESCRIPTION
**Pull request by ashudeep-sharma**
Fixes #1994

### CODE REVIEW

File: go/vt/logutil/purge.go [hunk 1]
```diff
@@ -22,7 +22,8 @@ func parseTimestamp(filename string) (timestamp time.Time, err error) {
 	if len(parts) < 6 {
 		return time.Time{}, fmt.Errorf("malformed logfile name: %v", filename)
 	}
-	return time.Parse("20060102-150405", parts[5])
+	//return time.Parse("20060102-150405", parts[5])
```
Comment (harshit-gangal) [inline go/vt/logutil/purge.go]: Remove this comment.

**Comment by enisoc** [comment]
LGTM. I'll merge when Travis finishes.
