### PR TITLE
fix vtexplain to handle semicolons better

### LINKED ISSUE #3337: vtexplain syntax error on embedded semi-colon in SQL
A syntax error occurs when a semi-colon appears in the -sql argument or in the file of the -sql-file argument either inside a comment or inside a string.

**OK**

    $ vtexplain -sql='select 1 from b /* * */' -schema='create table b(id int)' -vschema='{"K":{"tables":{"b":{}}}}'
    ----------------------------------------------------------------------
    select 1 from b
    
    1 K/-: select 1 from b limit 10001
    
    ----------------------------------------------------------------------

**FAIL**

    $ vtexplain -sql='select 1 from b /* ; */' -schema='create table b(id int)' -vschema='{"K":{"tables":{"b":{}}}}'
    ERROR: vtexplain execute error: syntax error at position 20 near '/* ' in select 1 from b /* 

    $ vtexplain -sql='select 1 from b where id = ";"' -schema='create table b(id int)' -vschema='{"K":{"tables":{"b":{}}}}'
    ERROR: vtexplain execute error: syntax error at position 29 in select 1 from b where id = "

    $ vtexplain -sql='select ";" from b' -schema='create table b(id int)' -vschema='{"K":{"tables":{"b":{}}}}'
    ERROR: vtexplain execute error: syntax error at position 9 in select "

(I actually found it by replaying a query with `_binary '$binary_data'`, resulting in a less-than-straightforward debugging session.)

### PR DESCRIPTION
**Pull request by demmer**
Add a utilty function `sqlparser.SplitStatement` that divides the input buffer into the first sql statement up to ; and the remainder.

Use this in vtexplain when dividing the inputs for both the schema and the sql queries into separate statements for evaluation.

Fixes #3337

### CODE REVIEW

File: go/vt/sqlparser/ast.go [hunk 1]
```diff
@@ -97,6 +97,26 @@ func ParseNext(tokenizer *Tokenizer) (Statement, error) {
 	return tokenizer.ParseTree, nil
 }
 
+// SplitStatement returns the first sql statement up to either a ; or EOF
+// and the remainder from the given buffer
+func SplitStatement(blob string) (string, string, error) {
```
Comment (sougou) [inline go/vt/sqlparser/ast.go]: I think you can just use sqlparser.ParseNext instead.

Comment (demmer) [reply go/vt/sqlparser/ast.go]: I started there, but I didn't want to actually bother parsing the tree since I wanted to distinguish between any scanner errors and parser errors.

I can probably switch back but this seemed pretty straightforward.

**Comment by sougou** [comment]
LGTM
